spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dukbab
    username: root
    password: 1234
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true


#    spring.jpa.hibernate.ddl-auto=update
#    spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#    spring.datasource.url=jdbc:mariadb://localhost:3306/dukbab
#    spring.datasource.username=root
#    spring.datasource.password=1234
