spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/dukbab
    username: root
    password: 1234
  jpa:
<<<<<<< HEAD
    hibernate: 
      ddl-auto: update
=======
    hibernate:
      ddl-auto: update  # create-drop 시 db를 자동으로 생성해 줌.
>>>>>>> origin/back-end
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: ZHVrYmFiU2VjcmV0S2V5ZHVrYmFiU2VjcmV0S2V5ZHVrYmFiU2VjcmV0S2V5ZHVrYmFiU2VjcmV0S2V5ZHVrYmFiU2VjcmV0S2V5


#    spring.jpa.hibernate.ddl-auto=update
#    spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#    spring.datasource.url=jdbc:mariadb://localhost:3306/dukbab
#    spring.datasource.username=root
#    spring.datasource.password=1234
